_BASE_: "../base_fpn.yaml"
INPUT:
  FIXED_INPUT_SIZE: false
MODEL:
  BACKBONE:
    CONFIG:
      OUT_FEATURES:
        - stages.0
        - stages.1
        - stages.2
        - stages.3
      PRETRAINED: true
      REMAPS:
        - stage1
        - stage2
        - stage3
        - stage4
      REMOVE_LAYERS:
        - final_conv
        - head
      STRIDES:
        - 4
        - 8
        - 16
        - 32
      CHANNELS:
        - 96
        - 192
        - 384
        - 512
      # FREEZE_AT: 2
      FREEZE_LAYERS:
        - stem
        - stage1
        - stage2
    NAME: "build_regnetz_e8_fpn_backbone"
  DEVICE: cuda
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES:
      - stage1
      - stage2
      - stage3
      - stage4
    NORM: ''
    OUT_CHANNELS: 256
OUTPUT_DIR: "../logs/regnetz_e8_fpn/"
SOLVER:
  BASE_LR: 0.02
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 16
  MAX_ITER: 90000
  STEPS:
    - 60000
    - 80000
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
