_BASE_: "../base_fpn.yaml"
INPUT:
  MAX_SIZE_TRAIN: 1120
  MAX_SIZE_TEST: 1120
  MIN_SIZE_TRAIN:
    - 1120
  MIN_SIZE_TEST: 1120
  FIXED_INPUT_SIZE: true
MODEL:
  BACKBONE:
    CONFIG:
      OUT_FEATURES:
        - layers.0.blocks.1
        - layers.1.blocks.1
        - layers.2.blocks.17
        - layers.3.blocks.1
      PRETRAINED: false
      REMAPS:
        - block1
        - block2
        - block3
        - block4
      REMOVE_LAYERS:
        - norm
        - avgpool
        - head
      STRIDES:
        - 4
        - 8
        - 16
        - 32
      CHANNELS:
        - 96
        - 192
        - 384
        - 768
      # REPLACE_LAYERS:
      #  - ['patch_embed', 'PatchEmbed']
    FREEZE_AT: 0
    NAME: "build_swin_small_patch4_window7_224_fpn_backbone"
  DEVICE: cuda
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES:
      - block1
      - block2
      - block3
      - block4
    NORM: ''
    OUT_CHANNELS: 256
OUTPUT_DIR: "../logs/swin_small_patch4_window7_224_fpn/"
SOLVER:
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 16
  MAX_ITER: 90000
  STEPS:
    - 60000
    - 80000
  WARMUP_FACTOR: 0.05
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
