_BASE_: "../base_fpn.yaml"
INPUT:
  MAX_SIZE_TRAIN: 1312
  MAX_SIZE_TEST: 1312
  MIN_SIZE_TRAIN:
    - 800
  MIN_SIZE_TEST: 800
  FIXED_INPUT_SIZE: true
MODEL:
  BACKBONE:
    CONFIG:
      OUT_FEATURES:
        - blocks.7
        - blocks.11
        - blocks.15
        - blocks.23
      PRETRAINED: False
      REMAPS:
        - block1
        - block2
        - block3
        - block4
      REMOVE_LAYERS:
        - blocks_token_only
        - norm
        - head
      STRIDES:
        - 4
        - 8
        - 16
        - 32
      CHANNELS:
        - 384
        - 384
        - 384
        - 384
    FREEZE_AT: 0
    NAME: "build_cait_s24_384_fpn_backbone"
  DEVICE: cuda
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES:
      - block1
      - block2
      - block3
      - block4
    NORM: ''
    OUT_CHANNELS: 256
OUTPUT_DIR: "../logs/cait_s24_384_fpn/"
SOLVER:
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 16
  MAX_ITER: 90000
  STEPS:
    - 60000
    - 80000
  WARMUP_FACTOR: 0.05
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
